#! /bin/bash
echo "Enter the value of n"
read n
a=0
b=1
count=2
echo "Fibonacci series:"
echo $a
echo $b
while [ $count -le $n ]
do
fib=`expr $a + $b`
a=$b
b=$fib
echo $fib
count=`expr $count + 1`
done

//for 4.2 ps -e | wc -l
// look for the output of ls -l
//pass that in'

cat | grep '^..r..r..r'

